// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqcmuajtpavfcyenjguy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxY211YWp0cGF2ZmN5ZW5qZ3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzQ2MDAsImV4cCI6MjA5MTE1MDYwMH0.2QQSuES4hSochJgCj6ritSZp4r9JPoyj-9NTAaa_yjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});